
--Consultas:

-- C1: Rastreabilidade reversa:
SELECT L.ID_LOTE, 
    FP.NOME AS PRODUTOR_RESPONSÁVEL, 
    FCQ.NOME AS CONTROLE_QUALIDADE,
    A.NOME AS AUDITOR_APROVOU,
    LISTAGG(LU.COD_BARRAS, ', ')
        WITHIN GROUP (ORDER BY LU.COD_BARRAS) AS INSUMOS_UTILIZADOS
        
    FROM LOTE L
    
    LEFT JOIN FUNCIONARIO FP
    ON L.CPF_PRODUTOR_RESP = FP.CPF
    
    LEFT JOIN FUNCIONARIO FCQ
    ON L.CPF_CONTROLE_QUALI = FCQ.CPF
    
    LEFT JOIN AUDITOR_APROVA_LOTE AL
    ON L.ID_LOTE = AL.ID_LOTE
    LEFT JOIN AUDITOR A
    ON A.CPF_AUD = AL.CPF_AUDITOR
    
    LEFT JOIN LOTE_UTILIZA_INSUMO LU
    ON L.ID_LOTE = LU.ID_LOTE
    
    WHERE L.ID_LOTE = 9
    
    GROUP BY L.ID_LOTE, FP.NOME, FCQ.NOME, A.NOME;

-- C4: RELAÇÃO DE CLIMA E PRODUTIVIDADE
SELECT DM.NOME_API AS APIARIO,
    AVG(DM.PRECIPITACAO) AS MÉDIA_PRECIPITAÇÃO,
    AVG(DM.RADIACAO) AS MÉDIA_RADIAÇÃO
    FROM DADO_METEREOLOGICO DM
    
    WHERE (SYSDATE - DM.DATA_HORA) < 60
    
    GROUP BY DM.NOME_API;

-- C8: Inventario de insumos externos:
SELECT IE.COD_BARRAS AS INSUMOS_EM_FALTA,
    I.PEGADA_CO2 AS EMISSÃO_CO2
    FROM INSUMO I
    
    LEFT JOIN INSUMO_EXTERNO IE ON I.COD_BARRAS = IE.COD_BARRAS
    
    WHERE I.QUANTIDADE < 50;
    
    
    
    
    