
--Consultas:

-- 1° Consulta:
-- C1: Rastreabilidade reversa:
SELECT L.ID_LOTE,
    FP.NOME AS PRODUTOR_RESPONSAVEL,
    FCQ.NOME AS CONTROLE_QUALIDADE,
    A.NOME AS AUDITOR_APROVOU,
    LISTAGG(LU.COD_BARRAS, ', ')
        WITHIN GROUP (ORDER BY LU.COD_BARRAS) AS INSUMOS_UTILIZADOS

    FROM LOTE L

    LEFT JOIN FUNCIONARIO FP
    ON L.CPF_PRODUTOR_RESP = FP.CPF

    LEFT JOIN FUNCIONARIO FCQ
    ON L.CPF_CONTROLE_QUALI = FCQ.CPF

    LEFT JOIN AUDITOR_APROVA_LOTE AL
    ON L.ID_LOTE = AL.ID_LOTE
    LEFT JOIN AUDITOR A
    ON A.CPF_AUD = AL.CPF_AUDITOR

    LEFT JOIN LOTE_UTILIZA_INSUMO LU
    ON L.ID_LOTE = LU.ID_LOTE

    WHERE L.ID_LOTE = 9

    GROUP BY L.ID_LOTE, FP.NOME, FCQ.NOME, A.NOME;

-- 2° Consulta:
-- C4: RELAÇÃO DE CLIMA E PRODUTIVIDADE
SELECT DM.NOME_API AS APIARIO,
    AVG(DM.PRECIPITACAO) AS MEDIA_PRECIPITACAO,
    AVG(DM.RADIACAO) AS MEDIA_RADIACAO
    FROM DADO_METEREOLOGICO DM

    WHERE (SYSDATE - DM.DATA_HORA) < 60

    GROUP BY DM.NOME_API;

-- 3° Consulta:
-- C8: Inventario de insumos externos:
SELECT IE.COD_BARRAS AS INSUMOS_EM_FALTA,
    I.PEGADA_CO2 AS EMISSAO_CO2
    FROM INSUMO I

    LEFT JOIN INSUMO_EXTERNO IE ON I.COD_BARRAS = IE.COD_BARRAS

    WHERE I.QUANTIDADE < 50;

-- 4° Consulta:
-- C6: Eficiência dos apicultores:

-- 5° Consulta:
-- C7: Produtividade dos tecnicos:
