INSERT INTO FUNCIONARIO (CPF, NOME, TELEFONE, ENDEREÇO, EMAIL, DATA_CONTRATACAO, SALARIO_BASE, CARTEIRA_TRABALHO, VINCULO_EMPREGATICIO, FUNCAO) 
    VALUES ('458', 'Nicolas', 16987456, 'Araraquara, rua joaquim, N°63', 'alcoriz@gmail.com', TO_DATE('2018/04/30 16:00:00', 'YYYY/MM/DD HH24:MI:SS'), 1500, 458962, 'CLT', 'Apicultor');
INSERT INTO FUNCIONARIO (CPF, NOME, TELEFONE, ENDEREÇO, EMAIL, DATA_CONTRATACAO, SALARIO_BASE, CARTEIRA_TRABALHO, VINCULO_EMPREGATICIO, FUNCAO) 
    VALUES ('45896364985', 'Alvaro', 1756219863, 'Bauru, rua nelson, N°132', 'alfis@gmail.com', TO_DATE('2015/07/12 15:30:00', 'YYYY/MM/DD HH24:MI:SS'), 2900, 123692, 'Tercerizado', 'Tecnico');
INSERT INTO FUNCIONARIO (CPF, NOME, TELEFONE, ENDEREÇO, EMAIL, DATA_CONTRATACAO, SALARIO_BASE, CARTEIRA_TRABALHO, VINCULO_EMPREGATICIO, FUNCAO) 
    VALUES ('12458', 'Leonardo', 1145559836, 'Ubatuba, rua alves, N°29', 'alfab@gmail.com', TO_DATE('2011/10/12 19:30:00', 'YYYY/MM/DD HH24:MI:SS'), 5000, 598741, 'PJ', 'Produtor');

INSERT INTO DIPLOMA_FUNCIONARIO (CPF_FUN, DIPLOMA) VALUES ('458', NULL);    
INSERT INTO DIPLOMA_FUNCIONARIO (CPF_FUN, DIPLOMA) VALUES ('45896364985', NULL);

INSERT INTO AUDITOR (CPF_AUD, NOME, TELEFONE, ENDEREÇO, EMAIL, ESPECIALIDADE, REGISTRO, ORGAO) VALUES ('45236', 'Carlos', 126985475, 'santos, rua tabinque, n° 96', 'hondo5@gmail.com', 'Normas de segurança', 458, 'SP-INT');
INSERT INTO AUDITOR (CPF_AUD, NOME, TELEFONE, ENDEREÇO, EMAIL, ESPECIALIDADE, REGISTRO, ORGAO) VALUES ('458598', 'João', 15998003694, 'Recife, rua trabuco, n° 129', 'joãoperna@gmail.com', 'Toxicos e saúde', 186, 'BA-INT');

INSERT INTO APIARIO (NOME, CPF_RESPONSAVEL, AMBIENTE, ESTADO, CIDADE, RUA, NUMERO, COLMEIAS) VALUES ('Apiario Santa Helena', '12458', 'Cerrado', 'GO', 'Goiania', 'marcos toledo', 65, DEFAULT);
INSERT INTO APIARIO (NOME, CPF_RESPONSAVEL, AMBIENTE, ESTADO, CIDADE, RUA, NUMERO, COLMEIAS) VALUES ('Apiario Serra da mata', '458', 'Mata Atlantica', 'SP', 'Bariri', '14 de junho', 169, DEFAULT);
INSERT INTO APIARIO (NOME, CPF_RESPONSAVEL, AMBIENTE, ESTADO, CIDADE, RUA, NUMERO, COLMEIAS) VALUES ('Apiario Serra da mata', '458', 'Mata Atlantica', 'SP', 'Bariri', '14 de junho', 169, DEFAULT);

INSERT INTO FISCALIZACAO (NOME, CPF_AUD, DATA_FIS, VALIDADE, SELO, STATUS) VALUES ('Apiario Santa Helena', '45236', TO_DATE('2025/10/12 19:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2026/10/12 19:30:00', 'YYYY/MM/DD HH24:MI:SS'), 'B', 'Finalizada');

INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 1, 'ativa', 'Jatái', 20.125, 80.256);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 2, 'ativa', 'Jatái', 20.129, 80.251);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 3, 'ativa', 'Jatái', 20.131, 80.249);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 4, 'ativa', 'Jatái', 20.69, 90.015);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 5, 'ativa', 'Jatái', 20.69, 90.0);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 6, 'ativa', 'Jatái', 20.69, 179.9);

INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES (NULL, 7, 'ativa', 'Jatái', 20.12, 170.9);

INSERT INTO SENSOR (SERIE, NOME_API, COL_NUM, FABRICANTE, DATA_COMPRA) VALUES (1297, 'Apiario Santa Helena', 2, 'TROY TEC', TO_DATE('2026/01/12 09:00:00', 'YYYY/MM/DD HH24:MI:SS'));
INSERT INTO SENSOR (SERIE, NOME_API, COL_NUM, FABRICANTE, DATA_COMPRA) VALUES (459822, 'Apiario Santa Helena', 3, 'TROY TEC', TO_DATE('2025/01/12 09:00:00', 'YYYY/MM/DD HH24:MI:SS'));
INSERT INTO SENSOR (SERIE, NOME_API, COL_NUM, FABRICANTE, DATA_COMPRA) VALUES (89541, 'Apiario Santa Helena', 1, 'TROY TEC', TO_DATE('2025/07/12 09:00:00', 'YYYY/MM/DD HH24:MI:SS'));

INSERT INTO DADOS_COLMEIA (SERIE, NOME_API, COL_NUM, DATA_HORA, RUIDO, PESO, UMIDADE, TEMPERATURA) VALUES (1297, 'Apiario Santa Helena', 2, TO_DATE('2026/06/10 10:00:00', 'YYYY/MM/DD HH24:MI:SS'), 12.12, 15.1, 13.0, 20.4);
INSERT INTO DADOS_COLMEIA (SERIE, NOME_API, COL_NUM, DATA_HORA, RUIDO, PESO, UMIDADE, TEMPERATURA) VALUES (1297, 'Apiario Santa Helena', 2, TO_DATE('2026/06/10 11:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2.1, 1.1, 74.0, 25.4);

INSERT INTO DADO_METEREOLOGICO (NOME_API, DATA_HORA, VENTO, TEMPERATURA, UMIDADE, RADIACAO, PRECIPITACAO, PRESSAO) VALUES ('Apiario Santa Helena', TO_DATE('2022/06/10 10:00:00', 'YYYY/MM/DD HH24:MI:SS'), 72.0, 69.1, 0.15, NULL, NULL, NULL);

INSERT INTO PRODUTO (COD_BARRAS) VALUES ('0145874');
INSERT INTO PRODUTO (COD_BARRAS) VALUES ('0126984');
INSERT INTO PRODUTO (COD_BARRAS) VALUES ('0458799');

INSERT INTO INSUMO (COD_BARRAS, TIPO, QUANTIDADE, ORIGEM, OBSERVACOES, PEGADA_CO2, CERTIFICACAO_AMB) VALUES ('0145874', 'ferramenta manual', 4, 'externo', NULL, NULL, NULL);
INSERT INTO INSUMO (COD_BARRAS, TIPO, QUANTIDADE, ORIGEM, OBSERVACOES, PEGADA_CO2, CERTIFICACAO_AMB) VALUES ('0126984', 'embalagem de mel', 120, 'externo', 'Embalagens de mel fabricadas pelo fabricante Potes, utilizadas para o armazenamento do produto final.', NULL, NULL);
INSERT INTO INSUMO (COD_BARRAS, TIPO, QUANTIDADE, ORIGEM, OBSERVACOES, PEGADA_CO2, CERTIFICACAO_AMB) VALUES ('0458799', 'tampas de pote', 540, 'externo', NULL, NULL, NULL);

INSERT INTO INSUMO_EXTERNO (COD_BARRAS, FABRICANTE) VALUES ('0126984', 'Toyta');
INSERT INTO INSUMO_EXTERNO (COD_BARRAS, FABRICANTE) VALUES ('0458799', 'Toyta');
