INSERT INTO FUNCIONARIO (CPF, NOME, TELEFONE, ENDEREÇO, EMAIL, DATA_CONTRATACAO, SALARIO_BASE, CARTEIRA_TRABALHO, VINCULO_EMPREGATICIO, FUNCAO) 
    VALUES ('458', 'Nicolas', 16987456, 'Araraquara, rua joaquim, N°63', 'alcoriz@gmail.com', TO_DATE('2018/04/30 16:00:00', 'YYYY/MM/DD HH24:MI:SS'), 1500, 458962, 'CLT', 'Apicultor');
INSERT INTO FUNCIONARIO (CPF, NOME, TELEFONE, ENDEREÇO, EMAIL, DATA_CONTRATACAO, SALARIO_BASE, CARTEIRA_TRABALHO, VINCULO_EMPREGATICIO, FUNCAO) 
    VALUES ('45896364985', 'Alvaro', 1756219863, 'Bauru, rua nelson, N°132', 'alfis@gmail.com', TO_DATE('2015/07/12 15:30:00', 'YYYY/MM/DD HH24:MI:SS'), 2900, 123692, 'Tercerizado', 'Tecnico');
INSERT INTO FUNCIONARIO (CPF, NOME, TELEFONE, ENDEREÇO, EMAIL, DATA_CONTRATACAO, SALARIO_BASE, CARTEIRA_TRABALHO, VINCULO_EMPREGATICIO, FUNCAO) 
    VALUES ('12458', 'Leonardo', 1145559836, 'Ubatuba, rua alves, N°29', 'alfab@gmail.com', TO_DATE('2011/10/12 19:30:00', 'YYYY/MM/DD HH24:MI:SS'), 5000, 598741, 'PJ', 'Produtor');


INSERT INTO DIPLOMA_FUNCIONARIO (CPF_FUN, DIPLOMA) VALUES ('458', NULL);    
INSERT INTO DIPLOMA_FUNCIONARIO (CPF_FUN, DIPLOMA) VALUES ('45896364985', NULL);

INSERT INTO AUDITOR (CPF_AUD, NOME, TELEFONE, ENDEREÇO, EMAIL, ESPECIALIDADE, REGISTRO, ORGAO) VALUES ('45236', 'Carlos', 126985475, 'santos, rua tabinque, n° 96', 'hondo5@gmail.com', 'Normas de segurança', 458, 'SP-INT');
INSERT INTO AUDITOR (CPF_AUD, NOME, TELEFONE, ENDEREÇO, EMAIL, ESPECIALIDADE, REGISTRO, ORGAO) VALUES ('458598', 'João', 15998003694, 'Recife, rua trabuco, n° 129', 'joãoperna@gmail.com', 'Toxicos e saúde', 186, 'BA-INT');

INSERT INTO APIARIO (NOME, CPF_RESPONSAVEL, AMBIENTE, ESTADO, CIDADE, RUA, NUMERO, COLMEIAS) VALUES ('Apiario Santa Helena', '12458', 'Cerrado', 'GO', 'Goiania', 'marcos toledo', 65, DEFAULT);
INSERT INTO APIARIO (NOME, CPF_RESPONSAVEL, AMBIENTE, ESTADO, CIDADE, RUA, NUMERO, COLMEIAS) VALUES ('Apiario Serra da mata', '458', 'Mata Atlantica', 'SP', 'Bariri', '14 de junho', 169, DEFAULT);

INSERT INTO FISCALIZACAO (NOME, CPF_AUD, DATA_FIS, VALIDADE, SELO, STATUS) VALUES ('Apiario Santa Helena', '45236', TO_DATE('2025/10/12 19:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2026/10/12 19:30:00', 'YYYY/MM/DD HH24:MI:SS'), 'B', 'Finalizada');

INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 1, 'ativa', 'Jatái', 20.125, 80.256);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 2, 'ativa', 'Jatái', 20.129, 80.251);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 3, 'ativa', 'Jatái', 20.131, 80.249);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 4, 'ativa', 'Jatái', 20.69, 90.015);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 5, 'ativa', 'Jatái', 20.69, 90.0);
INSERT INTO COLMEIA (NOME_COL, NUMERO, ESTADO, ESPECIE, LATITUDE, LONGITUDE) VALUES ('Apiario Santa Helena', 6, 'ativa', 'Jatái', 20.69, 180.0);



