CREATE TABLE FUNCIONARIO (
   CPF VARCHAR2(14) NOT NULL,
   NOME VARCHAR2(30),
   TELEFONE NUMBER(14),
   ENDEREÇO VARCHAR2(60),
   EMAIL VARCHAR2(30),
   DATA_CONTRATACAO DATE NOT NULL,
   SALARIO_BASE NUMBER(10, 2) NOT NULL,
   CARTEIRA_TRABALHO NUMBER(10) NOT NULL,
   VINCULO_EMPREGATICIO VARCHAR2(12) NOT NULL,
   FUNCAO VARCHAR2(20) NOT NULL,

   CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CPF),
   CONSTRAINT CK_VINCULO_EMPREGATICIO CHECK(UPPER(VINCULO_EMPREGATICIO) IN ('CLT', 'PJ', 'AUTÔNOMO', 'TERCERIZADO')),
   CONSTRAINT CK_FUNCAO CHECK(UPPER(FUNCAO) IN ('TECNICO', 'APICULTOR', 'SUPERVISOR', 'CONTROLE QUALIDADE', 'PRODUTOR'))
   );
   
CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_CPF
    BEFORE INSERT OR UPDATE ON FUNCIONARIO
    FOR EACH ROW
    DECLARE
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AUDITOR
        WHERE CPF = :NEW.CPF;

        IF V_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(
                -20001,
                'CPF já cadastrado como auditor.'
            );
        END IF;
    END;
    /
   
CREATE TABLE DIPLOMA_FUNCIONARIO (
    CPF_FUN VARCHAR2(14) NOT NULL,
    DIPLOMA BLOB,
    
    CONSTRAINT FK_DIPLOMA_FUNCIONARIO FOREIGN KEY (CPF_FUN) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);

CREATE TABLE AUDITOR (
    CPF_AUD VARCHAR2(14) NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    TELEFONE NUMBER(14),
    ENDEREÇO VARCHAR2(60),
    EMAIL VARCHAR2(30),
    ESPECIALIDADE VARCHAR2(60) NOT NULL,
    REGISTRO NUMBER(10) NOT NULL,
    ORGAO VARCHAR2(6) NOT NULL,
    
    CONSTRAINT PK_AUDITOR PRIMARY KEY(CPF_AUD)
);

CREATE OR REPLACE TRIGGER TRG_AUDITOR_CPF
    BEFORE INSERT OR UPDATE ON AUDITOR
    FOR EACH ROW
    DECLARE
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM FUNCIONARIO
        WHERE CPF = :NEW.CPF_AUD;

        IF V_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(
                -20001,
                'CPF já cadastrado como funcionário.'
            );
        END IF;
    END;
    /
    
CREATE TABLE APIARIO (
    NOME VARCHAR2(30) NOT NULL,
    CPF_RESPONSAVEL VARCHAR2(14) NOT NULL,
    AMBIENTE VARCHAR2(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR2(20) NOT NULL,
    RUA VARCHAR2(20) NOT NULL,
    NUMERO NUMBER(4,0) NOT NULL,
    COLMEIAS NUMBER(4,0) DEFAULT 0,
    
    -- Como fazer a verificação do numero de colmeias?
    -- Apenas um funcionario na função de supervisor pode ser responsavel
    CONSTRAINT PK_APIARIO PRIMARY KEY(NOME),
    CONSTRAINT FK_APIARIO FOREIGN KEY (CPF_RESPONSAVEL) REFERENCES FUNCIONARIO(CPF)
    );
    
CREATE TABLE FISCALIZACAO (
    NOME VARCHAR2(30),
    CPF_AUD VARCHAR2(14),
    DATA_FIS DATE,
    VALIDADE DATE NOT NULL,
    SELO CHAR(1) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_FISCALIZACAO PRIMARY KEY(NOME, CPF_AUD),
    CONSTRAINT FK_NOME FOREIGN KEY (NOME) REFERENCES APIARIO(NOME),
    CONSTRAINT FK_CPF_AUD FOREIGN KEY (CPF_AUD) REFERENCES AUDITOR(CPF_AUD)
    );
    
CREATE TABLE COLMEIA (
    NOME_COL VARCHAR2(30),
    NUMERO NUMBER(4, 0) NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    ESPECIE VARCHAR2(20) NOT NULL,
    LATITUDE NUMBER(9,6) NOT NULL,
    LONGITUDE NUMBER(9,6) NOT NULL,
    
     -- restrição dos dados de latitude(+- 90) e longitude(+- 180)
    CONSTRAINT CK_COORDENADA_LAT CHECK(LATITUDE > -90.0 AND LATITUDE < 90.0),
    CONSTRAINT CK_COORDENADA_LON CHECK(LONGITUDE > -180.0 AND LONGITUDE < 180.0),
    
    CONSTRAINT PK_COLMEIA PRIMARY KEY(NOME_COL, NUMERO),
    CONSTRAINT FK_NOME_COL FOREIGN KEY (NOME_COL) REFERENCES APIARIO(NOME)
    );
    
CREATE TABLE SENSOR (
    SERIE NUMBER(7, 0),
    );


