CREATE TABLE FUNCIONARIO (
   CPF VARCHAR2(14),
   NOME VARCHAR2(30),
   TELEFONE NUMBER(14),
   ENDEREÇO VARCHAR2(60),
   EMAIL VARCHAR2(30),
   DATA_CONTRATACAO DATE NOT NULL,
   SALARIO_BASE NUMBER(10, 2) NOT NULL,
   CARTEIRA_TRABALHO NUMBER(10) NOT NULL,
   VINCULO_EMPREGATICIO VARCHAR2(12) NOT NULL,
   FUNCAO VARCHAR2(20) NOT NULL,

   CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CPF),
   CONSTRAINT CK_VINCULO_EMPREGATICIO CHECK(UPPER(VINCULO_EMPREGATICIO) IN ('CLT', 'PJ', 'AUTÔNOMO', 'TERCERIZADO')),
   CONSTRAINT CK_FUNCAO CHECK(UPPER(FUNCAO) IN ('TECNICO', 'APICULTOR', 'SUPERVISOR', 'CONTROLE QUALIDADE', 'PRODUTOR'))
   );
   
CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_CPF
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM AUDITOR
    WHERE CPF_AUD = :NEW.CPF;

    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'CPF já cadastrado como auditor.'
        );
    END IF;
END;
/
   
CREATE TABLE DIPLOMA_FUNCIONARIO (
    CPF_FUN VARCHAR2(14) NOT NULL,
    DIPLOMA BLOB,
    
    CONSTRAINT PK_DIPLOMA_FUNCIONARIO PRIMARY KEY(CPF_FUN),
    CONSTRAINT FK_DIPLOMA_FUNCIONARIO FOREIGN KEY (CPF_FUN) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);

CREATE TABLE AUDITOR (
    CPF_AUD VARCHAR2(14),
    NOME VARCHAR2(30) NOT NULL,
    TELEFONE NUMBER(14),
    ENDEREÇO VARCHAR2(60),
    EMAIL VARCHAR2(30),
    ESPECIALIDADE VARCHAR2(60) NOT NULL,
    REGISTRO NUMBER(10) NOT NULL,
    ORGAO VARCHAR2(6) NOT NULL,
    
    CONSTRAINT PK_AUDITOR PRIMARY KEY(CPF_AUD)
);

CREATE OR REPLACE TRIGGER TRG_AUDITOR_CPF
BEFORE INSERT OR UPDATE ON AUDITOR
FOR EACH ROW
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM FUNCIONARIO
    WHERE CPF = :NEW.CPF_AUD;

    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'CPF já cadastrado como funcionário.'
        );
    END IF;
END;
/
    
CREATE TABLE APIARIO (
    NOME VARCHAR2(30),
    CPF_RESPONSAVEL VARCHAR2(14) NOT NULL,
    AMBIENTE VARCHAR2(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR2(20) NOT NULL,
    RUA VARCHAR2(20) NOT NULL,
    NUMERO NUMBER(4,0) NOT NULL,
    COLMEIAS NUMBER(4,0) DEFAULT 0,
    
    CONSTRAINT PK_APIARIO PRIMARY KEY(NOME),
    CONSTRAINT FK_APIARIO FOREIGN KEY (CPF_RESPONSAVEL) REFERENCES FUNCIONARIO(CPF),
    CONSTRAINT UK_APIARIO UNIQUE (CPF_RESPONSAVEL) 
    );
    
-- Trigger para verificar se o responsavel é supervisor:    
CREATE OR REPLACE TRIGGER TRG_RESPONSAVEL_APIARIO
BEFORE INSERT OR UPDATE ON APIARIO
FOR EACH ROW
DECLARE
    T_FUNCAO VARCHAR2(20);
BEGIN
    SELECT FUNCAO
    INTO T_FUNCAO
    FROM FUNCIONARIO
    WHERE CPF = :NEW.CPF_RESPONSAVEL;
    
    IF UPPER(T_FUNCAO) != 'SUPERVISOR' THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'Funcionario não ocupa a função de supervisor.'
        );
    END IF;
END;
/
    
CREATE TABLE FISCALIZACAO (
    NOME VARCHAR2(30),
    CPF_AUD VARCHAR2(14),
    DATA_FIS DATE,
    VALIDADE DATE NOT NULL,
    SELO CHAR(1) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_FISCALIZACAO PRIMARY KEY(NOME, CPF_AUD),
    CONSTRAINT FK_NOME FOREIGN KEY (NOME) REFERENCES APIARIO(NOME) ON DELETE CASCADE,
    CONSTRAINT FK_CPF_AUD FOREIGN KEY (CPF_AUD) REFERENCES AUDITOR(CPF_AUD)
    );
    
CREATE TABLE COLMEIA (
    NOME_COL VARCHAR2(30),
    NUMERO NUMBER(4, 0),
    ESTADO VARCHAR2(20) NOT NULL,
    ESPECIE VARCHAR2(20) NOT NULL,
    LATITUDE NUMBER(9,6) NOT NULL,
    LONGITUDE NUMBER(9,6) NOT NULL,
    
     -- restrição dos dados de latitude(+- 90) e longitude(+- 180)
    CONSTRAINT CK_COORDENADA_LAT CHECK(LATITUDE > -90.0 AND LATITUDE < 90.0),
    CONSTRAINT CK_COORDENADA_LON CHECK(LONGITUDE > -180.0 AND LONGITUDE < 180.0),
    
    CONSTRAINT PK_COLMEIA PRIMARY KEY(NOME_COL, NUMERO),
    CONSTRAINT FK_NOME_COL FOREIGN KEY (NOME_COL) REFERENCES APIARIO(NOME) ON DELETE CASCADE
    );

-- Trigger que atualiza o numero total de colmeias em cada apiario:
CREATE OR REPLACE TRIGGER TRG_CONTA_COLMEIAS
AFTER INSERT ON COLMEIA
FOR EACH ROW
BEGIN
    UPDATE APIARIO
    SET COLMEIAS = COLMEIAS + 1
    WHERE NOME = :NEW.NOME_COL;
END;
/
    
CREATE TABLE SENSOR (
    SERIE NUMBER(7, 0),
    NOME_API VARCHAR2(30),
    COL_NUM NUMBER(4,0),
    FABRICANTE VARCHAR2(30),
    DATA_COMPRA DATE,
    
    CONSTRAINT PK_SENSOR PRIMARY KEY(SERIE),
    CONSTRAINT FK_API_COL FOREIGN KEY (NOME_API, COL_NUM) REFERENCES COLMEIA(NOME_COL, NUMERO) ON DELETE SET NULL,
    CONSTRAINT UK_SENSOR UNIQUE (NOME_API, COL_NUM),
    CONSTRAINT UK_SENSOR_PS UNIQUE (SERIE, NOME_API, COL_NUM) --Sem isso o oracle não referencia a tabela de dados_colmeia
    );
    
CREATE TABLE DADOS_COLMEIA (
    SERIE NUMBER(7, 0),
    NOME_API VARCHAR2(30),
    COL_NUM NUMBER(4,0),
    DATA_HORA DATE,
    RUIDO NUMBER(5,2),
    PESO NUMBER(5,2),
    UMIDADE NUMBER(5,2),
    TEMPERATURA NUMBER(5,2),
    
    CONSTRAINT PK_DADOS_COL PRIMARY KEY(SERIE, NOME_API, COL_NUM, DATA_HORA),
    CONSTRAINT FK_SENSOR_API_COL FOREIGN KEY (SERIE, NOME_API, COL_NUM) REFERENCES SENSOR(SERIE, NOME_API, COL_NUM) ON DELETE CASCADE
    --possivel restrição dos tipos de dados inseridos?
    );
    
CREATE TABLE DADO_METEREOLOGICO (
    NOME_API VARCHAR2(30),
    DATA_HORA DATE,
    VENTO NUMBER(5,2),
    TEMPERATURA NUMBER(5,2),
    UMIDADE NUMBER(5,2),
    RADIACAO NUMBER(5,2),
    PRECIPITACAO NUMBER(5,2),
    PRESSAO NUMBER(5,2),
    
    CONSTRAINT PK_DADO_CLIMA PRIMARY KEY(NOME_API, DATA_HORA),
    CONSTRAINT FK_DADO_CLIMA FOREIGN KEY (NOME_API) REFERENCES APIARIO(NOME) ON DELETE CASCADE
    --possivel restrição dos tipos de dados inseridos?
    );
    
CREATE TABLE PRODUTO (
    COD_BARRAS VARCHAR2(20),
    
    CONSTRAINT PK_PRODUTO PRIMARY KEY(COD_BARRAS)
    );
    
CREATE TABLE INSUMO (
    COD_BARRAS VARCHAR2(20),
    TIPO VARCHAR2(30) NOT NULL,
    QUANTIDADE NUMBER(5,2) NOT NULL,
    ORIGEM VARCHAR2(30) NOT NULL,
    OBSERVACOES CLOB,
    PEGADA_CO2 VARCHAR2(30),
    CERTIFICACAO_AMB VARCHAR2(30),
    
    CONSTRAINT PK_INSUMO PRIMARY KEY(COD_BARRAS),
    CONSTRAINT FK_INSUMO FOREIGN KEY (COD_BARRAS) REFERENCES PRODUTO(COD_BARRAS) ON DELETE CASCADE,
    CONSTRAINT CK_ORIGEM CHECK(UPPER(ORIGEM) IN ('EXTERNO', 'INTERNO')) 
    );
    
CREATE TABLE INSUMO_EXTERNO (
    COD_BARRAS VARCHAR2(20),
    FABRICANTE VARCHAR2(30),
    
    CONSTRAINT PK_INSUMO_EXT PRIMARY KEY(COD_BARRAS),
    CONSTRAINT FK_INSUMO_EXT FOREIGN KEY (COD_BARRAS) REFERENCES INSUMO(COD_BARRAS) ON DELETE CASCADE
    );
    
-- Trigger para verificar se o novo insumo externo é externo:    
CREATE OR REPLACE TRIGGER TRG_INSUMO_EXTERNO
BEFORE INSERT OR UPDATE ON INSUMO_EXTERNO
FOR EACH ROW
DECLARE
    T_ORIGEM VARCHAR2(30);
BEGIN
    SELECT ORIGEM
    INTO T_ORIGEM
    FROM INSUMO
    WHERE COD_BARRAS = :NEW.COD_BARRAS;
    
    IF UPPER(T_ORIGEM) != 'EXTERNO' THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'Insumo não é de origem externa.'
        );
    END IF;
END;
/

CREATE TABLE INTERVENCAO (
    ID_SINTETICO NUMBER GENERATED ALWAYS AS IDENTITY, --cria um id sequencial automaticamente
    NOME_API VARCHAR2(30),
    NUM_COL NUMBER(4,0),
    DATA_INTERVENCAO DATE,
    CPF_RESP VARCHAR2(14) NOT NULL,
    CPF_APICULTOR VARCHAR2(14) NOT NULL, --Problema: 1 responsavel por intervenção, mas varios apicultores por intervenção
    TIPO VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_INTERVENCAO PRIMARY KEY(ID_SINTETICO),
    CONSTRAINT FK_INTERVENCAO_COL FOREIGN KEY (NOME_API, NUM_COL) REFERENCES COLMEIA(NOME_COL, NUMERO) ON DELETE CASCADE,
    CONSTRAINT FK_INTER_RESP FOREIGN KEY (CPF_RESP) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_INTER_APICULTOR FOREIGN KEY (CPF_APICULTOR) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT UK_INTERVENCAO_2 UNIQUE (NOME_API, NUM_COL, DATA_INTERVENCAO),
    --CONSTRAINT UK_INTERVENCAO_3 UNIQUE (CPF_RESP, CPF_APICULTOR), --Essa chave terciaria não faz sentido
    CONSTRAINT CK_INTERVENCAO CHECK(UPPER(TIPO) IN ('EXTRACAO', 'MANUTENSAO'))
    );
    
CREATE TABLE RELATORIO (
    NOME VARCHAR2(100),
    DATA DATE NOT NULL,
    DATA_CHANGE DATE,
    --TIPO: esse atributo faz algum sentido??
    ID_INTERVENCAO NUMBER,
    
    CONSTRAINT PK_RELATORIO PRIMARY KEY(NOME),
    CONSTRAINT FK_RELATORIO FOREIGN KEY (ID_INTERVENCAO) REFERENCES INTERVENCAO(ID_SINTETICO) ON DELETE CASCADE,
    CONSTRAINT UK_RELATORIO UNIQUE (ID_INTERVENCAO)
    );
    
DROP TABLE INSUMO_INTERNO CASCADE CONSTRAINTS;
    
CREATE TABLE INSUMO_INTERNO(
    COD_BARRAS VARCHAR2(20),
    ID_INTERVENCAO NUMBER NOT NULL,
    
    CONSTRAINT PK_INSUMO_INT PRIMARY KEY(COD_BARRAS),
    CONSTRAINT FK_INSUMO_INT FOREIGN KEY (COD_BARRAS) REFERENCES INSUMO(COD_BARRAS),
    CONSTRAINT FK_INSUMO_INT_1 FOREIGN KEY (ID_INTERVENCAO) REFERENCES INTERVENCAO(ID_SINTETICO) 
    );
    
-- Trigger para verificar se o novo insumo externo é externo:    
CREATE OR REPLACE TRIGGER TRG_INSUMO_EXTERNO
BEFORE INSERT OR UPDATE ON INSUMO_EXTERNO
FOR EACH ROW
DECLARE
    T_ORIGEM VARCHAR2(30);
BEGIN
    SELECT ORIGEM
    INTO T_ORIGEM
    FROM INSUMO
    WHERE COD_BARRAS = :NEW.COD_BARRAS;
    
    IF UPPER(T_ORIGEM) != 'EXTERNO' THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'Insumo não é de origem externa.'
        );
    END IF;
END;
/
    


