
--Consultas:

-- 1° Consulta:
-- C1: Rastreabilidade reversa:
SELECT L.ID_LOTE,
    FP.NOME AS PRODUTOR_RESPONSAVEL,
    FCQ.NOME AS CONTROLE_QUALIDADE,
    A.NOME AS AUDITOR_APROVOU,
    X.INSUMOS AS INSUMOS_UTILIZADOS,
    I.NOME_API AS APIARIO_ORIGEM

    FROM LOTE L

    LEFT JOIN FUNCIONARIO FP
    ON L.CPF_PRODUTOR_RESP = FP.CPF

    LEFT JOIN FUNCIONARIO FCQ
    ON L.CPF_CONTROLE_QUALI = FCQ.CPF

    LEFT JOIN AUDITOR_APROVA_LOTE AL
    ON L.ID_LOTE = AL.ID_LOTE
    LEFT JOIN AUDITOR A
    ON A.CPF_AUD = AL.CPF_AUDITOR
    
    JOIN (
    SELECT ID_LOTE,
           LISTAGG(COD_BARRAS, ', ')
               WITHIN GROUP (ORDER BY COD_BARRAS) AS INSUMOS
    FROM LOTE_UTILIZA_INSUMO
    GROUP BY ID_LOTE
        ) X
    ON X.ID_LOTE = L.ID_LOTE
    
    LEFT JOIN LOTE_UTILIZA_INSUMO LU
    ON L.ID_LOTE = LU.ID_LOTE AND (LU.ID_EXTRACAO IS NOT NULL)
    LEFT JOIN INTERVENCAO I
    ON LU.ID_EXTRACAO = I.ID_SINTETICO

    WHERE L.ID_LOTE = 3;
    

-- 2° Consulta:
-- C4: RELAÇÃO DE CLIMA E PRODUTIVIDADE
SELECT DM.NOME_API AS APIARIO,
    AVG(DM.PRECIPITACAO) AS MEDIA_PRECIPITACAO,
    AVG(DM.RADIACAO) AS MEDIA_RADIACAO
    FROM DADO_METEREOLOGICO DM

    WHERE (SYSDATE - DM.DATA_HORA) < 60

    GROUP BY DM.NOME_API;

-- 3° Consulta:
-- C8: Inventario de insumos externos:
SELECT IE.COD_BARRAS AS INSUMOS_EM_FALTA,
    I.PEGADA_CO2 AS EMISSAO_CO2
    FROM INSUMO I

    RIGHT JOIN INSUMO_EXTERNO IE ON I.COD_BARRAS = IE.COD_BARRAS

    WHERE I.QUANTIDADE < 600;

-- 4° Consulta:
-- C6: Eficiência dos apicultores:
SELECT I.CPF_RESP AS APICULTOR_RESPONSAVEL,
    AVG(AL.NOTA) AS MEDIA_QUALIDADE

    FROM INTERVENCAO I
    
    LEFT JOIN LOTE_UTILIZA_INSUMO LI
    ON LI.ID_EXTRACAO = I.ID_SINTETICO
    
    LEFT JOIN AUDITOR_APROVA_LOTE AL
    ON AL.ID_LOTE = LI.ID_LOTE
    
    GROUP BY I.CPF_RESP
    ORDER BY AVG(AL.NOTA) DESC;

-- 5° Consulta:
-- C7: Produtividade dos tecnicos:
SELECT F.NOME AS NOME_TECNICO,
    COUNT(F.NOME) AS RELATORIOS_GERADOS

    FROM RELATORIO R

    RIGHT JOIN RELATORIO_TECNICO RT
    ON R.NOME = RT.NOME_REL
    
    RIGHT JOIN FUNCIONARIO F
    ON RT.CPF_TECNICO = F.CPF
    
    WHERE (SYSDATE-R.DATA) < 30
    
    GROUP BY F.NOME;
    
-- 6° Consulta:
-- Quais auditores participaram de todas as aprovações
-- dos lotes criados em um dado mês?
SELECT A.CPF_AUD AS CPF_AUDITOR,
    A.NOME AS NOME_AUDITOR

    FROM AUDITOR A
    JOIN AUDITOR_APROVA_LOTE AL
    ON A.CPF_AUD = AL.CPF_AUDITOR

    WHERE AL.ID_LOTE IN (
        SELECT ID_LOTE
        FROM LOTE
        WHERE EXTRACT(MONTH FROM DATA_PROD) = 1
        AND EXTRACT(YEAR FROM DATA_PROD) = 2026
    )

    GROUP BY A.CPF_AUD, A.NOME

    HAVING COUNT(DISTINCT AL.ID_LOTE) =
    (
        SELECT COUNT(*)
        FROM LOTE
        WHERE EXTRACT(MONTH FROM DATA_PROD) = 1
        AND EXTRACT(YEAR FROM DATA_PROD) = 2026
    );



